### ISSUE TITLE
 ModuleNotFoundError: No module named 'Cython'

### ISSUE THREAD

**Issue by Evarln1996** [ntucllab/libact#193]
As indicated in the title, when I run the "pip install libact" command, it says that the cython module is missing, even though it's installed correctly. I've uninstalled it, reinstalled it, but it doesn't work. I've also changed the version of python 3.6 to python 3.5.4 because I thought there might be an accounting problem, but it still doesn't work.

**Comment by yangarbiter** [comment]
Do you have any additional error message that can be provided? Can you also check if you can import cython correctly from your Python interpreter?

**Comment by Evarln1996** [comment]
When I type "pip install -vvv libact" to get more informations, I get that error message : 
`    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION

    import  numpy as np
    cimport numpy as np
    from libc.stdlib cimport free
    cimport _hintsvm
            ^
    ------------------------------------------------------------

    libact/query_strategies/_hintsvm.pyx:6:8: '_hintsvm.pxd' not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-v1y5l5yw/libact_10b1286b826841d2a0e89d5e14350303/setup.py", line 44, in <module>
        extra_compile_args=['-lstdc++'],
      File "/home/roline/miniconda3/envs/libact/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
        cythonize_one(*args)
      File "/home/roline/miniconda3/envs/libact/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: libact/query_strategies/_hintsvm.pyx
    Platform Detection: Linux. Link to liblapacke...
    Compiling libact/query_strategies/_hintsvm.pyx because it changed.
    [1/1] Cythonizing libact/query_strategies/_hintsvm.pyx
WARNING: Discarding https://files.pythonhosted.org/packages/71/28/5ef80e435f7e1b829fa5aa50d5ca81df09af11975314dcbf43a6ec1759a4/libact-0.1.1.tar.gz#sha256=d30352bbfaaaec435bcf6486aec290813af8bc5defc973d511993ea473a6d447 (from https://pypi.org/simple/libact/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement libact (from versions: 0.1.1, 0.1.1.post1, 0.1.1.post2, 0.1.1.post3, 0.1.2, 0.1.3b0, 0.1.3b1, 0.1.3, 0.1.4a0, 0.1.4, 0.1.5, 0.1.6)
ERROR: No matching distribution found for libact
`

**Comment by Evarln1996** [comment]
@yangarbiter can you give me the version of cython and liblapacke-dev? Because I'm having accounting problems

**Comment by yangarbiter** [comment]
Sorry for the late reply. There seems to be something wrong with the wheel building process. One temporary workaround is to download the source code and install from `python ./setup.py install`. Can you try that and let me know if that works?

**Comment by somritabanerjee** [comment]
I tried the above solution of installing from source. It didn't work, I still get the same error.

pip 23.0.1 
python 3.8

`python setup.py install` yields
```
libact % python setup.py install
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
```

 `pip install cython` yields
```
> × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [6 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/private/var/folders/gl/8gczjt_n2cs_09wy2zcwzx8m0000gn/T/pip-install-7tpgwpwg/libact_bf38513009054e42944dd11c26bb6c9c/setup.py", line 21, in <module>
>           from Cython.Build import cythonize
>       ModuleNotFoundError: No module named 'Cython'
```
